print(sorted([
      "bio_int_enhancer",
      "bio_carbon",
      "bio_chain_lightning",
      "bio_emp_armgun",
      "bio_magnet",
      "bio_nanobots",
      "bio_painkiller",
      "bio_ears",
      "bio_blood_filter",
      "bio_faraday",
            "bio_power_storage_mkII",
      "bio_power_storage_mkII",
      "bio_power_storage_mkII",
      "bio_power_storage_mkII",
      "bio_power_storage_mkII",
      "bio_power_storage_mkII",
      "bio_power_storage_mkII",
      "bio_power_storage_mkII",
      "bio_railgun",
      "bio_remote",
      "bio_resonator",
      "bio_cutting_torch",
      "bio_batteries",
      "bio_cable",
      "bio_purifier",
      "bio_tools",
      "bio_razors",
      "bio_ups",
      "bio_sunglasses",      "bio_power_armor_interface_mkII",
      "bio_fuel_cell_gasoline",
      "bio_digestion",
      "bio_water_extractor",
      "bio_heat_absorb",
      "bio_metabolics",
      "bio_sword",
      "bio_plasma_cell"
    ]))


    